[package]
name = "neonet_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
cw-storage-plus = "1.0.0"

[dev-dependencies]
cosmwasm-schema = "1.0.0"
